In [1]:
# Importing the necessary library
import pandas as pd
import numpy as np

In [ ]:
# 0. Data load

# Dataset loading
df = pd.read_csv('D:\Project\Titenic Dataset Insights Using Pandas & NumPy\Titanic-Dataset.csv') # Convert the DataFrame into the CSV
print(df.head()) # First fice rows shows

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

Explanation:

pd.read_csv() → loads CSV into a DataFrame

head() → shows first 5 rows

In [ ]:
# 1. Basic Data Exploration (Pandas)
# (A) Shape, column, info

print('Missing values in each column')
df.shape # row, columns
df.columns # column names
df.info() # datatypes + null count

Missing values in each column
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Explanation:

shape → (rows, columns)

columns → list of column names

info() → data types + non-null counts

In [ ]:
# (B) Summary Statistics

df.describe() # States of numeric columns: mean, std, min/max
df.describe(include="object") # Stats of column object: unique, top, freq

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

Explanation:

describe() → numeric stats (mean, std, min, max)

include="object" → categorical stats (unique, top value)

In [ ]:
# 2. Missing Values (Null Handinling)
# (A) Count Missing Values
df.isna().sum().sort_values(ascending=False)

Explanation:

isna() → checks null values

sum() → counts missing

sort_values() → sorts highest missing first

In [ ]:
# (B) Missing Percentage
(df.isna().mean() * 100).sort_values(ascending=False)

Cabin          77.104377
Age            19.865320
Embarked        0.224467
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
dtype: float64

In [33]:
# Selecting Data
# (A) Select Columns

df["Age"].head()
df[["Age","Sex", "Survived"]].head()

    Age     Sex  Survived
0  22.0    male         0
1  38.0  female         1
2  26.0  female         1
3  35.0  female         1
4  35.0    male         0

In [35]:
# (B) Filter Rows(Conditions)
df[df["Sex"] == "female"].head()
df[(df["Age"] > 30) & (df["Pclass"] == 1)].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup,FamilySize
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Young,2
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Adult,1
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Adult,1
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C,Adult,1

Explanation:

& → AND condition

| → OR condition

In [21]:
# 4. Sorting and Value Counts

df.sort_values("Fare", ascending=False).head(10)

df["Sex"].value_counts()

df["Pclass"].value_counts(normalize=True) * 100

Pclass
3    55.106622
1    24.242424
2    20.650954
Name: proportion, dtype: float64

Explanation:

sort_values() → sorts rows

value_counts() → category frequency

normalize=True → percentage

In [22]:
# 5. GroupBy
# (A) Survival Rate by Gender

df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

Explanation:

Since Survived = 0 or 1

Mean = survival rate

In [23]:
# (B) Survival by Class and Gender

df.groupby(["Pclass", "Sex"])["Survived"].mean()

Pclass  Sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

In [24]:
# (C) Multiple Aggregations

df.groupby("Pclass").agg(
    avg_fare=("Fare", "mean"),
    max_fare=("Fare", "max"),
    total_passengers=("PassengerId", "count")
)

         avg_fare  max_fare  total_passengers
Pclass
1       84.154687  512.3292               216
2       20.662183   73.5000               184
3       13.675550   69.5500               491

In [ ]:
# 6️. Creating New Features
# (A) Create Age Groups

df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 35, 60, 100],
    labels=["Child", "Teen", "Young", "Adult", "Senior"]
)

df[["Age", "AgeGroup"]].head()

    Age AgeGroup
0  22.0    Young
1  38.0    Adult
2  26.0    Young
3  35.0    Young
4  35.0    Young

Explanation:

pd.cut() → converts continuous values into categories

In [26]:
# (B) Create Family Size

df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df[["SibSp", "Parch", "FamilySize"]].head()

   SibSp  Parch  FamilySize
0      1      0           2
1      1      0           2
2      0      0           1
3      1      0           2
4      0      0           1

In [38]:
# 7️. Handling Missing Values
# (A) Fill Age with Median

df["Age"] = df["Age"].fillna(df["Age"].median())

Why median?

Less affected by outliers

In [39]:
# (B) Fill Embarked with Mode

df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [40]:
# 8️. NumPy Practice on Titanic
# (A) Convert to NumPy Array

ages = df["Age"].to_numpy()
fares = df["Fare"].to_numpy()

ages[:10]

array([22., 38., 26., 35., 35., 28., 54.,  2., 27., 14.])

In [45]:
# (B) Mean, Median, Std

np.mean(ages)
np.median(ages)
np.std(ages)

print(np.mean(ages))
print(np.median(ages))
print(np.std(ages))

29.36158249158249
28.0
13.012388272793666

In [ ]:
# (C) Find Passengers with Fare Above Average

avg_fare = np.mean(fares)

indices = np.where(fares > avg_fare)[0]

df.iloc[indices][["Name", "Fare"]].head()

Explanation:

np.where() → returns index positions

iloc → index-based selection

In [46]:
# (D) Min-Max Normalization

fare_min = fares.min()
fare_max = fares.max()

fare_norm = (fares - fare_min) / (fare_max - fare_min)

fare_norm[:10]

array([0.01415106, 0.13913574, 0.01546857, 0.1036443 , 0.01571255,
       0.0165095 , 0.10122886, 0.04113566, 0.02173075, 0.05869429])

In [47]:
# 9️. Pivot Table

pd.pivot_table(
    df,
    values="Survived",
    index="Sex",
    columns="Pclass",
    aggfunc="mean"
)

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

Explanation:

Shows survival rate matrix by Gender vs Class